// Code generated by LangGraph. Do not edit.
import { render, screen } from '@testing-library/react';
import Footer from '../Footer';

describe('Footer Component', () => {
  it('renders dark background and social icons with correct classes', () => {
    render(<Footer />);
    
    expect(screen.getByText('Built with React')).toBeInTheDocument();
    // Add additional checks for social icons
    expect(screen.getByTestId('github-icon')).toBeInTheDocument();
    expect(screen.getByTestId('twitter-icon')).toBeInTheDocument();
    expect(screen.getByTestId('linkedin-icon')).toBeInTheDocument();
  });
});